### ISSUE TITLE
Prodigal Contracts

### ISSUE THREAD

**Issue by Yasir1515** [wesleyjtann/Safe-SmartContracts#2]
I see this project. . i find that Prodigal Contracts csv is missing. Also can you share the data that is used in this project? Specially the Prodigal Contracts csv.

**Comment by wesleyjtann** [comment]
Hi, the datasets are in the google drive link in the README file.

https://drive.google.com/drive/folders/1KuKxknJ-uOWZOaymP9b3eOXa1hFNZxVS?usp=sharing
