### ISSUE TITLE
missing input_data/final

### ISSUE THREAD

**Issue by BBO-repo** [wesleyjtann/Safe-SmartContracts#3]
Hello,
Thanks for this repository and the associated scientific article (Towards Safer Smart Contracts: A Sequence Learning Approach
to Detecting Security Threats).
I'm trying to retrieve the paper result and cloned this repo, but while trying to run the py scripts and/or jupyter notebook it is failing because no input_data/final folder exists.

Would it be possible to upload those data in the git repo? Or is there a way to retrieve this input_data/final folder content?

Regards.

**Comment by wesleyjtann** [comment]
Hi, our data is in the link below. Hope it helps.

https://drive.google.com/drive/folders/1KuKxknJ-uOWZOaymP9b3eOXa1hFNZxVS?usp=sharing

**Comment by BBO-repo** [comment]
Thanks for this prompt answer. 
I'll test it in the next few days and keep updated.

**Comment by BBO-repo** [comment]
Hello,
I tried to run the notebooks and script and using the latest version of tensorflow, etc... some import are broken.
I tried to repaired some of them but finally too much are broken.

I was wondering if you were working with virtual environment? If yes could you run a pip freeze to a requirement.txt and link it there to be able to use the same python modules and version as the one you're using.

Regards.
